modpack_name: "[05.001.00] Zombie Invade 100 Days"
modpack_url: "https://github.com/octoberserver/modpack-release/releases/download/05.001.00/05.001.00.Zombie.Invade.100.Days.zip"
version: "05.001.00"
