modpack_name: "[03.001.01] Closing Song IDP Modified"
modpack_url: "https://github.com/octoberserver/modpack-release/releases/download/untagged-8cc186c1744365406f5a/03.001.01.zip"
version: "03.001.01"
